# Generated by Django 5.2 on 2025-06-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bundles/'),
        ),
    ]
